name: run-bot

on:
  schedule:
    - cron: '0 * * * *'  # запуск каждый час
  workflow_dispatch:     # возможность ручного запуска

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download seen.json from artifacts
        uses: actions/download-artifact@v4
        with:
          name: seen-artifact
          path: .
        continue-on-error: true

      - name: Run bot
        run: python main.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Upload seen.json to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: seen-artifact
          path: seen.json